UPDATE biblioref_reference 
SET
  created_time = NOW() -- created_time - DATETIME NOT NULL
 ,updated_time = NOW() -- updated_time - DATETIME
 ,status = 0 -- status - SMALLINT(6)
 ,reference_title = 'Marcello' -- reference_title - LONGTEXT NOT NULL
 ,cooperative_center_code = '' -- cooperative_center_code - VARCHAR(55) NOT NULL
 ,literature_type = '' -- literature_type - VARCHAR(10) NOT NULL
 ,treatment_level = '' -- treatment_level - VARCHAR(10) NOT NULL
 ,electronic_address = '' -- electronic_address - LONGTEXT
 ,record_type = '' -- record_type - VARCHAR(10) NOT NULL
 ,descriptive_information = '' -- descriptive_information - LONGTEXT
 ,text_language = '' -- text_language - LONGTEXT NOT NULL
 ,internal_note = '' -- internal_note - LONGTEXT NOT NULL
 ,publication_date = '' -- publication_date - VARCHAR(250) NOT NULL
 ,publication_date_normalized = '' -- publication_date_normalized - VARCHAR(25) NOT NULL
 ,total_number_of_references = '' -- total_number_of_references - VARCHAR(100) NOT NULL
 ,time_limits_from = '' -- time_limits_from - VARCHAR(50) NOT NULL
 ,time_limits_to = '' -- time_limits_to - VARCHAR(50) NOT NULL
 ,person_as_subject = '' -- person_as_subject - LONGTEXT NOT NULL
 ,non_decs_region = '' -- non_decs_region - LONGTEXT NOT NULL
 ,abstract = '' -- abstract - LONGTEXT
 ,transfer_date_to_database = '' -- transfer_date_to_database - VARCHAR(20) NOT NULL
 ,author_keyword = '' -- author_keyword - LONGTEXT
 ,item_form = '' -- item_form - VARCHAR(10) NOT NULL
 ,type_of_computer_file = '' -- type_of_computer_file - VARCHAR(10) NOT NULL
 ,type_of_cartographic_material = '' -- type_of_cartographic_material - VARCHAR(10) NOT NULL
 ,type_of_journal = '' -- type_of_journal - VARCHAR(10) NOT NULL
 ,type_of_visual_material = '' -- type_of_visual_material - VARCHAR(10) NOT NULL
 ,specific_designation_of_the_material = '' -- specific_designation_of_the_material - VARCHAR(10) NOT NULL
 ,general_note = '' -- general_note - LONGTEXT NOT NULL
 ,formatted_contents_note = '' -- formatted_contents_note - LONGTEXT NOT NULL
 ,additional_physical_form_available_note = '' -- additional_physical_form_available_note - LONGTEXT NOT NULL
 ,reproduction_note = '' -- reproduction_note - LONGTEXT NOT NULL
 ,original_version_note = '' -- original_version_note - LONGTEXT NOT NULL
 ,institution_as_subject = '' -- institution_as_subject - LONGTEXT NOT NULL
 ,local_descriptors = '' -- local_descriptors - LONGTEXT NOT NULL
 ,software_version = '' -- software_version - VARCHAR(50) NOT NULL
 ,LILACS_original_id = '' -- LILACS_original_id - VARCHAR(8) NOT NULL
 ,created_by_id = 0 -- created_by_id - INT(11)
 ,updated_by_id = 0 -- updated_by_id - INT(11)
 ,check_tags = '' -- check_tags - LONGTEXT NOT NULL
 ,publication_type = '' -- publication_type - LONGTEXT NOT NULL
 ,LILACS_indexed = 0 -- LILACS_indexed - TINYINT(1) NOT NULL
 ,BIREME_reviewed = 0 -- BIREME_reviewed - TINYINT(1) NOT NULL
 ,interoperability_source = '' -- interoperability_source - VARCHAR(100) NOT NULL
 ,indexer_cc_code = '' -- indexer_cc_code - VARCHAR(55) NOT NULL
WHERE
  id = 20
;